-- HIS Supabase restore generated from OMC Registration.xlsx

-- All app tables are prefixed with HIS_One_

-- Run this whole file in Supabase Dashboard > SQL Editor.

BEGIN;

CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public."HIS_One_Patients" (
  "Patient_ID" TEXT PRIMARY KEY,
  "Title" TEXT,
  "First_Name" TEXT,
  "Last_Name" TEXT,
  "Gender" TEXT,
  "Date_of_Birth" TEXT,
  "Age" INTEGER,
  "Nationality" TEXT,
  "Occupation" TEXT,
  "Blood_Type" TEXT,
  "Phone_Number" TEXT,
  "Email" TEXT,
  "Address" TEXT,
  "District" TEXT,
  "Province" TEXT,
  "Organization_ID" TEXT,
  "Name_Org" TEXT,
  "Insurance_Company" TEXT,
  "Insurance_Code" TEXT,
  "Insured_Person_Name" TEXT,
  "Drug_Allergy" TEXT,
  "Underlying_Disease" TEXT,
  "Emergency_Name" TEXT,
  "Emergency_Contact" TEXT,
  "Emergency_Relation" TEXT,
  "Channel" TEXT,
  "Registration_Date" TEXT,
  "Time" TEXT,
  "Shift" TEXT,
  "Age_Group" TEXT,
  "Photo_URL" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Patient_ID" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Title" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "First_Name" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Last_Name" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Gender" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Date_of_Birth" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Age" INTEGER;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Nationality" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Occupation" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Blood_Type" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Phone_Number" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Email" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Address" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "District" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Province" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Organization_ID" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Name_Org" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Insurance_Company" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Insurance_Code" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Insured_Person_Name" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Drug_Allergy" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Underlying_Disease" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Emergency_Name" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Emergency_Contact" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Emergency_Relation" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Channel" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Registration_Date" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Time" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Shift" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Age_Group" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Photo_URL" TEXT;

ALTER TABLE public."HIS_One_Patients" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Patients" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Patients" ON public."HIS_One_Patients";

CREATE POLICY "anon_all_Patients" ON public."HIS_One_Patients" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Patients" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Visits" (
  "Row_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Import_Key" TEXT,
  "Visit_ID" TEXT,
  "Vital_ID" TEXT,
  "Date" TEXT,
  "Time" TEXT,
  "Patient_ID" TEXT,
  "Patient_Name" TEXT,
  "Age" INTEGER,
  "Gender" TEXT,
  "Site" TEXT,
  "In_Site" TEXT,
  "Onsite" TEXT,
  "Visit_Type" TEXT,
  "Chief_Complaint" TEXT,
  "Symptoms" TEXT,
  "BP" TEXT,
  "Temp" TEXT,
  "Weight" TEXT,
  "Height" TEXT,
  "Pulse" TEXT,
  "SpO2" TEXT,
  "BP_Systolic" TEXT,
  "BP_Diastolic" TEXT,
  "Respiratory_Rate" TEXT,
  "O2_Saturation" TEXT,
  "Pain_Score" TEXT,
  "BMI" TEXT,
  "BMI_Status" TEXT,
  "Revenue_Group" TEXT,
  "Mapped_Specialist" TEXT,
  "Services_List" TEXT,
  "Diagnosis" TEXT,
  "Treatment" TEXT,
  "Follow_Up_Date" TEXT,
  "Status" TEXT,
  "Recorded_By" TEXT,
  "Doctor" TEXT,
  "Doctor_Name" TEXT,
  "Department" TEXT,
  "Notes" TEXT,
  "Appointment_ID" TEXT,
  "Shift" TEXT,
  "Visit_Date" TEXT,
  "Visit_Time" TEXT,
  "Prescription_JSON" TEXT,
  "Lab_Orders_JSON" TEXT,
  "Discharge_Status" TEXT,
  "Physical_Exam" TEXT,
  "Advice" TEXT,
  "Follow_Up" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Row_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Import_Key" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Visit_ID" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Vital_ID" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Date" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Time" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Patient_ID" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Patient_Name" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Age" INTEGER;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Gender" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Site" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "In_Site" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Onsite" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Visit_Type" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Chief_Complaint" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Symptoms" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "BP" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Temp" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Weight" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Height" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Pulse" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "SpO2" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "BP_Systolic" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "BP_Diastolic" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Respiratory_Rate" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "O2_Saturation" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Pain_Score" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "BMI" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "BMI_Status" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Revenue_Group" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Mapped_Specialist" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Services_List" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Diagnosis" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Treatment" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Follow_Up_Date" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Status" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Recorded_By" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Doctor" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Doctor_Name" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Department" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Appointment_ID" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Shift" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Visit_Date" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Visit_Time" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Prescription_JSON" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Lab_Orders_JSON" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Discharge_Status" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Physical_Exam" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Advice" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Follow_Up" TEXT;

ALTER TABLE public."HIS_One_Visits" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Visits" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Visits" ON public."HIS_One_Visits";

CREATE POLICY "anon_all_Visits" ON public."HIS_One_Visits" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Visits" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Appointments" (
  "Appt_ID" TEXT PRIMARY KEY,
  "Appointment_ID" TEXT,
  "Target_ID" TEXT,
  "Target_Name" TEXT,
  "Patient_ID" TEXT,
  "Patient_Name" TEXT,
  "Appt_Date" TEXT,
  "Appt_Time" TEXT,
  "Type" TEXT,
  "Reason" TEXT,
  "Doctor" TEXT,
  "Doctor_Name" TEXT,
  "Status" TEXT,
  "Created_Date" TEXT,
  "Created_By" TEXT,
  "Updated_Date" TEXT,
  "Department" TEXT,
  "Contact_Number" TEXT,
  "Notes" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Appt_ID" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Appointment_ID" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Target_ID" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Target_Name" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Patient_ID" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Patient_Name" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Appt_Date" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Appt_Time" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Type" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Reason" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Doctor" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Doctor_Name" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Status" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Created_Date" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Created_By" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Updated_Date" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Department" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Contact_Number" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_Appointments" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Appointments" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Appointments" ON public."HIS_One_Appointments";

CREATE POLICY "anon_all_Appointments" ON public."HIS_One_Appointments" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Appointments" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Organizations" (
  "Org_ID" TEXT PRIMARY KEY,
  "Cus_ID_Ex" TEXT,
  "Name" TEXT,
  "Org_Name" TEXT,
  "Org_Code" TEXT,
  "Discount" TEXT,
  "Status" TEXT,
  "Organization_ID" TEXT,
  "Organization_Name" TEXT,
  "Patient_ID" TEXT,
  "Title" TEXT,
  "First_Name" TEXT,
  "Last_Name" TEXT,
  "Gender" TEXT,
  "Date_of_Birth" TEXT,
  "Age" INTEGER,
  "Family_Member" TEXT,
  "Discount_Detail" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Org_ID" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Cus_ID_Ex" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Name" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Org_Name" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Org_Code" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Discount" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Status" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Organization_ID" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Organization_Name" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Patient_ID" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Title" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "First_Name" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Last_Name" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Gender" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Date_of_Birth" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Age" INTEGER;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Family_Member" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Discount_Detail" TEXT;

ALTER TABLE public."HIS_One_Organizations" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Organizations" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Organizations" ON public."HIS_One_Organizations";

CREATE POLICY "anon_all_Organizations" ON public."HIS_One_Organizations" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Organizations" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Service_Lists" (
  "ID" TEXT PRIMARY KEY,
  "Services_List" TEXT,
  "Mapped_Specialist" TEXT,
  "Revenue_Group" TEXT,
  "Medicine" TEXT,
  "unit" TEXT,
  "Usage" TEXT,
  "Note" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "ID" TEXT;

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "Services_List" TEXT;

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "Mapped_Specialist" TEXT;

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "Revenue_Group" TEXT;

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "Medicine" TEXT;

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "unit" TEXT;

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "Usage" TEXT;

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "Note" TEXT;

ALTER TABLE public."HIS_One_Service_Lists" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Service_Lists" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Service_Lists" ON public."HIS_One_Service_Lists";

CREATE POLICY "anon_all_Service_Lists" ON public."HIS_One_Service_Lists" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Service_Lists" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Locations" (
  "ID" TEXT PRIMARY KEY,
  "District" TEXT,
  "Province" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Locations" ADD COLUMN IF NOT EXISTS "ID" TEXT;

ALTER TABLE public."HIS_One_Locations" ADD COLUMN IF NOT EXISTS "District" TEXT;

ALTER TABLE public."HIS_One_Locations" ADD COLUMN IF NOT EXISTS "Province" TEXT;

ALTER TABLE public."HIS_One_Locations" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Locations" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Locations" ON public."HIS_One_Locations";

CREATE POLICY "anon_all_Locations" ON public."HIS_One_Locations" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Locations" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_MasterData" (
  "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Category" TEXT,
  "Value" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_MasterData" ADD COLUMN IF NOT EXISTS "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public."HIS_One_MasterData" ADD COLUMN IF NOT EXISTS "Category" TEXT;

ALTER TABLE public."HIS_One_MasterData" ADD COLUMN IF NOT EXISTS "Value" TEXT;

ALTER TABLE public."HIS_One_MasterData" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_MasterData" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_MasterData" ON public."HIS_One_MasterData";

CREATE POLICY "anon_all_MasterData" ON public."HIS_One_MasterData" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_MasterData" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Drugs_Master" (
  "Drug_ID" TEXT PRIMARY KEY,
  "Drug_Name" TEXT,
  "Description" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Drugs_Master" ADD COLUMN IF NOT EXISTS "Drug_ID" TEXT;

ALTER TABLE public."HIS_One_Drugs_Master" ADD COLUMN IF NOT EXISTS "Drug_Name" TEXT;

ALTER TABLE public."HIS_One_Drugs_Master" ADD COLUMN IF NOT EXISTS "Description" TEXT;

ALTER TABLE public."HIS_One_Drugs_Master" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Drugs_Master" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Drugs_Master" ON public."HIS_One_Drugs_Master";

CREATE POLICY "anon_all_Drugs_Master" ON public."HIS_One_Drugs_Master" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Drugs_Master" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Labs_Master" (
  "Lab_ID" TEXT PRIMARY KEY,
  "Lab_Name" TEXT,
  "Description" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Labs_Master" ADD COLUMN IF NOT EXISTS "Lab_ID" TEXT;

ALTER TABLE public."HIS_One_Labs_Master" ADD COLUMN IF NOT EXISTS "Lab_Name" TEXT;

ALTER TABLE public."HIS_One_Labs_Master" ADD COLUMN IF NOT EXISTS "Description" TEXT;

ALTER TABLE public."HIS_One_Labs_Master" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Labs_Master" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Labs_Master" ON public."HIS_One_Labs_Master";

CREATE POLICY "anon_all_Labs_Master" ON public."HIS_One_Labs_Master" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Labs_Master" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Vaccines_Master" (
  "Vac_ID" TEXT PRIMARY KEY,
  "Vaccine_Name" TEXT,
  "Disease" TEXT,
  "Disease_Target" TEXT,
  "Total_Doses" INTEGER,
  "Interval_Days" TEXT,
  "Dose_Interval" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Vaccines_Master" ADD COLUMN IF NOT EXISTS "Vac_ID" TEXT;

ALTER TABLE public."HIS_One_Vaccines_Master" ADD COLUMN IF NOT EXISTS "Vaccine_Name" TEXT;

ALTER TABLE public."HIS_One_Vaccines_Master" ADD COLUMN IF NOT EXISTS "Disease" TEXT;

ALTER TABLE public."HIS_One_Vaccines_Master" ADD COLUMN IF NOT EXISTS "Disease_Target" TEXT;

ALTER TABLE public."HIS_One_Vaccines_Master" ADD COLUMN IF NOT EXISTS "Total_Doses" INTEGER;

ALTER TABLE public."HIS_One_Vaccines_Master" ADD COLUMN IF NOT EXISTS "Interval_Days" TEXT;

ALTER TABLE public."HIS_One_Vaccines_Master" ADD COLUMN IF NOT EXISTS "Dose_Interval" TEXT;

ALTER TABLE public."HIS_One_Vaccines_Master" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Vaccines_Master" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Vaccines_Master" ON public."HIS_One_Vaccines_Master";

CREATE POLICY "anon_all_Vaccines_Master" ON public."HIS_One_Vaccines_Master" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Vaccines_Master" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Patient_Vaccines" (
  "Record_ID" TEXT PRIMARY KEY,
  "Patient_ID" TEXT,
  "Patient_Name" TEXT,
  "Vaccine_Name" TEXT,
  "Dose_Number" INTEGER,
  "Lot_Number" TEXT,
  "Date_Given" TEXT,
  "Next_Appointment_Date" TEXT,
  "Next_Due_Date" TEXT,
  "Given_By" TEXT,
  "Status" TEXT,
  "Notes" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Record_ID" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Patient_ID" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Patient_Name" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Vaccine_Name" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Dose_Number" INTEGER;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Lot_Number" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Date_Given" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Next_Appointment_Date" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Next_Due_Date" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Given_By" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Status" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_Patient_Vaccines" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Patient_Vaccines" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Patient_Vaccines" ON public."HIS_One_Patient_Vaccines";

CREATE POLICY "anon_all_Patient_Vaccines" ON public."HIS_One_Patient_Vaccines" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Patient_Vaccines" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Users" (
  "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" TEXT,
  "Email" TEXT UNIQUE,
  "Password" TEXT,
  "Password_Hash" TEXT,
  "Role" TEXT,
  "Permissions" TEXT,
  "ButtonPermissions" JSONB DEFAULT '{}'::jsonb,
  "Status" TEXT DEFAULT 'active',
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "Name" TEXT;

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "Email" TEXT UNIQUE;

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "Password" TEXT;

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "Password_Hash" TEXT;

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "Role" TEXT;

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "Permissions" TEXT;

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "ButtonPermissions" JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "Status" TEXT DEFAULT 'active';

ALTER TABLE public."HIS_One_Users" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Users" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Users" ON public."HIS_One_Users";

CREATE POLICY "anon_all_Users" ON public."HIS_One_Users" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Users" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Settings" (
  "Key" TEXT PRIMARY KEY,
  "Value" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Settings" ADD COLUMN IF NOT EXISTS "Key" TEXT;

ALTER TABLE public."HIS_One_Settings" ADD COLUMN IF NOT EXISTS "Value" TEXT;

ALTER TABLE public."HIS_One_Settings" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Settings" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Settings" ON public."HIS_One_Settings";

CREATE POLICY "anon_all_Settings" ON public."HIS_One_Settings" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Settings" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_activity_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" TIMESTAMPTZ,
  "user_id" TEXT,
  "user_name" TEXT,
  "action" TEXT,
  "details" TEXT,
  "module" TEXT
);

ALTER TABLE public."HIS_One_activity_logs" ADD COLUMN IF NOT EXISTS "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public."HIS_One_activity_logs" ADD COLUMN IF NOT EXISTS "timestamp" TIMESTAMPTZ;

ALTER TABLE public."HIS_One_activity_logs" ADD COLUMN IF NOT EXISTS "user_id" TEXT;

ALTER TABLE public."HIS_One_activity_logs" ADD COLUMN IF NOT EXISTS "user_name" TEXT;

ALTER TABLE public."HIS_One_activity_logs" ADD COLUMN IF NOT EXISTS "action" TEXT;

ALTER TABLE public."HIS_One_activity_logs" ADD COLUMN IF NOT EXISTS "details" TEXT;

ALTER TABLE public."HIS_One_activity_logs" ADD COLUMN IF NOT EXISTS "module" TEXT;

ALTER TABLE public."HIS_One_activity_logs" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_activity_logs" ON public."HIS_One_activity_logs";

CREATE POLICY "anon_all_activity_logs" ON public."HIS_One_activity_logs" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_activity_logs" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Admissions" (
  "Admission_ID" TEXT PRIMARY KEY,
  "Patient_ID" TEXT,
  "Patient_Name" TEXT,
  "Admission_Date" TEXT,
  "Admission_Time" TEXT,
  "Admission_Type" TEXT,
  "Admitting_Doctor" TEXT,
  "Diagnosis_Admission" TEXT,
  "Ward_ID" TEXT,
  "Room_ID" TEXT,
  "Bed_ID" TEXT,
  "Deposit_Amount" NUMERIC,
  "Insurance_Info" TEXT,
  "Status" TEXT DEFAULT 'Admitted',
  "Discharge_Date" TEXT,
  "Discharge_Time" TEXT,
  "Discharge_Status" TEXT,
  "Discharge_Diagnosis" TEXT,
  "Notes" TEXT,
  "Follow_Up_Date" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Admission_ID" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Patient_ID" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Patient_Name" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Admission_Date" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Admission_Time" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Admission_Type" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Admitting_Doctor" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Diagnosis_Admission" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Ward_ID" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Room_ID" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Bed_ID" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Deposit_Amount" NUMERIC;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Insurance_Info" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Status" TEXT DEFAULT 'Admitted';

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Discharge_Date" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Discharge_Time" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Discharge_Status" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Discharge_Diagnosis" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Follow_Up_Date" TEXT;

ALTER TABLE public."HIS_One_Admissions" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Admissions" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Admissions" ON public."HIS_One_Admissions";

CREATE POLICY "anon_all_Admissions" ON public."HIS_One_Admissions" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Admissions" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Wards" (
  "Ward_ID" TEXT PRIMARY KEY,
  "Ward_Name" TEXT,
  "Department" TEXT,
  "Floor" TEXT,
  "Capacity" INTEGER,
  "Status" TEXT DEFAULT 'Active',
  "Notes" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Wards" ADD COLUMN IF NOT EXISTS "Ward_ID" TEXT;

ALTER TABLE public."HIS_One_Wards" ADD COLUMN IF NOT EXISTS "Ward_Name" TEXT;

ALTER TABLE public."HIS_One_Wards" ADD COLUMN IF NOT EXISTS "Department" TEXT;

ALTER TABLE public."HIS_One_Wards" ADD COLUMN IF NOT EXISTS "Floor" TEXT;

ALTER TABLE public."HIS_One_Wards" ADD COLUMN IF NOT EXISTS "Capacity" INTEGER;

ALTER TABLE public."HIS_One_Wards" ADD COLUMN IF NOT EXISTS "Status" TEXT DEFAULT 'Active';

ALTER TABLE public."HIS_One_Wards" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_Wards" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Wards" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Wards" ON public."HIS_One_Wards";

CREATE POLICY "anon_all_Wards" ON public."HIS_One_Wards" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Wards" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Rooms" (
  "Room_ID" TEXT PRIMARY KEY,
  "Ward_ID" TEXT,
  "Room_Number" TEXT,
  "Room_Type" TEXT,
  "Capacity" INTEGER,
  "Status" TEXT DEFAULT 'Available',
  "Notes" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Rooms" ADD COLUMN IF NOT EXISTS "Room_ID" TEXT;

ALTER TABLE public."HIS_One_Rooms" ADD COLUMN IF NOT EXISTS "Ward_ID" TEXT;

ALTER TABLE public."HIS_One_Rooms" ADD COLUMN IF NOT EXISTS "Room_Number" TEXT;

ALTER TABLE public."HIS_One_Rooms" ADD COLUMN IF NOT EXISTS "Room_Type" TEXT;

ALTER TABLE public."HIS_One_Rooms" ADD COLUMN IF NOT EXISTS "Capacity" INTEGER;

ALTER TABLE public."HIS_One_Rooms" ADD COLUMN IF NOT EXISTS "Status" TEXT DEFAULT 'Available';

ALTER TABLE public."HIS_One_Rooms" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_Rooms" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Rooms" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Rooms" ON public."HIS_One_Rooms";

CREATE POLICY "anon_all_Rooms" ON public."HIS_One_Rooms" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Rooms" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Beds" (
  "Bed_ID" TEXT PRIMARY KEY,
  "Room_ID" TEXT,
  "Ward_ID" TEXT,
  "Bed_Number" TEXT,
  "Status" TEXT DEFAULT 'Available',
  "Notes" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Beds" ADD COLUMN IF NOT EXISTS "Bed_ID" TEXT;

ALTER TABLE public."HIS_One_Beds" ADD COLUMN IF NOT EXISTS "Room_ID" TEXT;

ALTER TABLE public."HIS_One_Beds" ADD COLUMN IF NOT EXISTS "Ward_ID" TEXT;

ALTER TABLE public."HIS_One_Beds" ADD COLUMN IF NOT EXISTS "Bed_Number" TEXT;

ALTER TABLE public."HIS_One_Beds" ADD COLUMN IF NOT EXISTS "Status" TEXT DEFAULT 'Available';

ALTER TABLE public."HIS_One_Beds" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_Beds" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Beds" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Beds" ON public."HIS_One_Beds";

CREATE POLICY "anon_all_Beds" ON public."HIS_One_Beds" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Beds" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Progress_Notes" (
  "Note_ID" TEXT PRIMARY KEY,
  "Admission_ID" TEXT,
  "Note_Date" TEXT,
  "Note_Time" TEXT,
  "Doctor_Name" TEXT,
  "Note_Type" TEXT,
  "Subjective" TEXT,
  "Objective" TEXT,
  "Assessment" TEXT,
  "Plan" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Note_ID" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Admission_ID" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Note_Date" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Note_Time" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Doctor_Name" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Note_Type" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Subjective" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Objective" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Assessment" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Plan" TEXT;

ALTER TABLE public."HIS_One_Progress_Notes" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Progress_Notes" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Progress_Notes" ON public."HIS_One_Progress_Notes";

CREATE POLICY "anon_all_Progress_Notes" ON public."HIS_One_Progress_Notes" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Progress_Notes" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_IPD_Medications" (
  "Med_ID" TEXT PRIMARY KEY,
  "Admission_ID" TEXT,
  "Drug_Name" TEXT,
  "Dosage" TEXT,
  "Frequency" TEXT,
  "Route" TEXT,
  "Start_Date" TEXT,
  "End_Date" TEXT,
  "Notes" TEXT,
  "Status" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Med_ID" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Admission_ID" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Drug_Name" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Dosage" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Frequency" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Route" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Start_Date" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "End_Date" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Status" TEXT;

ALTER TABLE public."HIS_One_IPD_Medications" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_IPD_Medications" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_IPD_Medications" ON public."HIS_One_IPD_Medications";

CREATE POLICY "anon_all_IPD_Medications" ON public."HIS_One_IPD_Medications" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_IPD_Medications" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_IPD_Vital_Signs" (
  "Vital_ID" TEXT PRIMARY KEY,
  "Admission_ID" TEXT,
  "Record_Date" TEXT,
  "Record_Time" TEXT,
  "BP" TEXT,
  "Temp" NUMERIC,
  "Pulse" INTEGER,
  "Resp_Rate" INTEGER,
  "SpO2" INTEGER,
  "Pain_Score" INTEGER,
  "Consciousness" TEXT,
  "Notes" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Vital_ID" TEXT;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Admission_ID" TEXT;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Record_Date" TEXT;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Record_Time" TEXT;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "BP" TEXT;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Temp" NUMERIC;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Pulse" INTEGER;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Resp_Rate" INTEGER;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "SpO2" INTEGER;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Pain_Score" INTEGER;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Consciousness" TEXT;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_IPD_Vital_Signs" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_IPD_Vital_Signs" ON public."HIS_One_IPD_Vital_Signs";

CREATE POLICY "anon_all_IPD_Vital_Signs" ON public."HIS_One_IPD_Vital_Signs" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_IPD_Vital_Signs" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_Nursing_Notes" (
  "Note_ID" TEXT PRIMARY KEY,
  "Admission_ID" TEXT,
  "Note_Date" TEXT,
  "Note_Time" TEXT,
  "Nurse_Name" TEXT,
  "Note_Type" TEXT,
  "Content" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_Nursing_Notes" ADD COLUMN IF NOT EXISTS "Note_ID" TEXT;

ALTER TABLE public."HIS_One_Nursing_Notes" ADD COLUMN IF NOT EXISTS "Admission_ID" TEXT;

ALTER TABLE public."HIS_One_Nursing_Notes" ADD COLUMN IF NOT EXISTS "Note_Date" TEXT;

ALTER TABLE public."HIS_One_Nursing_Notes" ADD COLUMN IF NOT EXISTS "Note_Time" TEXT;

ALTER TABLE public."HIS_One_Nursing_Notes" ADD COLUMN IF NOT EXISTS "Nurse_Name" TEXT;

ALTER TABLE public."HIS_One_Nursing_Notes" ADD COLUMN IF NOT EXISTS "Note_Type" TEXT;

ALTER TABLE public."HIS_One_Nursing_Notes" ADD COLUMN IF NOT EXISTS "Content" TEXT;

ALTER TABLE public."HIS_One_Nursing_Notes" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_Nursing_Notes" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_Nursing_Notes" ON public."HIS_One_Nursing_Notes";

CREATE POLICY "anon_all_Nursing_Notes" ON public."HIS_One_Nursing_Notes" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_Nursing_Notes" TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public."HIS_One_IPD_Visits" (
  "Visit_ID" TEXT PRIMARY KEY,
  "Admission_ID" TEXT,
  "Visit_Date" TEXT,
  "Visit_Time" TEXT,
  "Visitor_Type" TEXT,
  "Visitor_Name" TEXT,
  "Visit_Purpose" TEXT,
  "Notes" TEXT,
  "Created_At" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Visit_ID" TEXT;

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Admission_ID" TEXT;

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Visit_Date" TEXT;

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Visit_Time" TEXT;

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Visitor_Type" TEXT;

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Visitor_Name" TEXT;

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Visit_Purpose" TEXT;

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Notes" TEXT;

ALTER TABLE public."HIS_One_IPD_Visits" ADD COLUMN IF NOT EXISTS "Created_At" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public."HIS_One_IPD_Visits" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_all_IPD_Visits" ON public."HIS_One_IPD_Visits";

CREATE POLICY "anon_all_IPD_Visits" ON public."HIS_One_IPD_Visits" FOR ALL TO anon USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public."HIS_One_IPD_Visits" TO anon, authenticated;

CREATE UNIQUE INDEX IF NOT EXISTS "uq_HIS_One_MasterData_Category_Value" ON public."HIS_One_MasterData" ("Category", "Value");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_HIS_One_Visits_Import_Key" ON public."HIS_One_Visits" ("Import_Key");

CREATE INDEX IF NOT EXISTS "idx_HIS_One_Patients_Registration_Date" ON public."HIS_One_Patients" ("Registration_Date");

CREATE INDEX IF NOT EXISTS "idx_HIS_One_Visits_Date" ON public."HIS_One_Visits" ("Date");

CREATE INDEX IF NOT EXISTS "idx_HIS_One_Visits_Status" ON public."HIS_One_Visits" ("Status");

CREATE INDEX IF NOT EXISTS "idx_HIS_One_Visits_Patient_ID" ON public."HIS_One_Visits" ("Patient_ID");

CREATE INDEX IF NOT EXISTS "idx_HIS_One_Appointments_Appt_Date" ON public."HIS_One_Appointments" ("Appt_Date");

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

COMMIT;

NOTIFY pgrst, 'reload schema';

-- Quick verification after running:

-- SELECT COUNT(*) FROM public."HIS_One_Patients";

-- SELECT COUNT(*) FROM public."HIS_One_Visits";

-- SELECT COUNT(*) FROM public."HIS_One_Organizations";
