function clean(value) {
  return String(value ?? '').trim();
}

function mapAssignmentRow(row = {}) {
  return {
    id: clean(row.ID),
    date: clean(row.Duty_Date),
    shift: clean(row.Shift),
    staffId: clean(row.Staff_ID),
    status: clean(row.Status) || 'working',
    replacementStaffId: clean(row.Replacement_Staff_ID),
    note: clean(row.Note),
    createdAt: clean(row.Created_At),
    updatedAt: clean(row.Updated_At)
  };
}

function mapHistoryRow(row = {}) {
  return {
    id: clean(row.ID),
    assignmentId: clean(row.Assignment_ID),
    action: clean(row.Action),
    date: clean(row.Duty_Date),
    shift: clean(row.Shift),
    staffId: clean(row.Staff_ID),
    staffName: clean(row.Staff_Name),
    staffType: clean(row.Staff_Type),
    statusBefore: clean(row.Status_Before),
    statusAfter: clean(row.Status_After),
    replacementBeforeId: clean(row.Replacement_Before_ID),
    replacementBeforeName: clean(row.Replacement_Before_Name),
    replacementAfterId: clean(row.Replacement_After_ID),
    replacementAfterName: clean(row.Replacement_After_Name),
    changedAt: clean(row.Changed_At),
    changedBy: clean(row.Changed_By_Name) || clean(row.Changed_By) || '-'
  };
}

function assignmentPayload(record = {}) {
  return {
    ID: clean(record.id) || undefined,
    Duty_Date: clean(record.date),
    Shift: clean(record.shift),
    Staff_ID: clean(record.staffId),
    Status: clean(record.status) || 'working',
    Replacement_Staff_ID: clean(record.replacementStaffId) || null,
    Note: clean(record.note) || null
  };
}

function errorMessage(scope, error) {
  const details = clean(error?.details || error?.hint);
  return `${scope}: ${clean(error?.message) || 'Unknown database error'}${details ? ` (${details})` : ''}`;
}

export function createManpowerSupabaseBackend({ client, assignmentsTableName, historyTableName }) {
  if (!client || !assignmentsTableName || !historyTableName) throw new Error('Manpower Supabase backend requires client and table names');
  let channel = null;

  return {
    mode: 'supabase',

    async loadAssignments(date) {
      let query = client
        .from(assignmentsTableName)
        .select('ID,Duty_Date,Shift,Staff_ID,Status,Replacement_Staff_ID,Note,Created_At,Updated_At')
        .is('Deleted_At', null)
        .order('Shift', { ascending: true })
        .order('Created_At', { ascending: true });
      if (clean(date)) query = query.eq('Duty_Date', clean(date));
      const { data, error } = await query;
      if (error) throw new Error(errorMessage('Manpower assignments', error));
      return (data || []).map(mapAssignmentRow);
    },

    async loadHistory(filters = {}) {
      let query = client
        .from(historyTableName)
        .select('ID,Assignment_ID,Action,Duty_Date,Shift,Staff_ID,Staff_Name,Staff_Type,Status_Before,Status_After,Replacement_Before_ID,Replacement_Before_Name,Replacement_After_ID,Replacement_After_Name,Changed_By,Changed_By_Name,Changed_At')
        .order('Changed_At', { ascending: false })
        .limit(2000);
      if (clean(filters.date)) query = query.eq('Duty_Date', clean(filters.date));
      if (clean(filters.shift)) query = query.eq('Shift', clean(filters.shift));
      if (clean(filters.type)) query = query.eq('Staff_Type', clean(filters.type));
      if (clean(filters.action)) query = query.eq('Action', clean(filters.action));
      const { data, error } = await query;
      if (error) throw new Error(errorMessage('Manpower history', error));
      return (data || []).map(mapHistoryRow);
    },

    async create(record) {
      const payload = assignmentPayload(record);
      // Production identifiers are always generated by Postgres. Local preview
      // identifiers may not be UUIDs and must never leak into the live table.
      delete payload.ID;
      const { data, error } = await client
        .from(assignmentsTableName)
        .insert(payload)
        .select('ID,Duty_Date,Shift,Staff_ID,Status,Replacement_Staff_ID,Note,Created_At,Updated_At')
        .single();
      if (error) throw new Error(errorMessage('Create manpower assignment', error));
      return mapAssignmentRow(data);
    },

    async update(id, changes = {}) {
      const payload = {
        Status: clean(changes.status) || 'working',
        Replacement_Staff_ID: clean(changes.replacementStaffId) || null,
        Note: clean(changes.note) || null
      };
      const { data, error } = await client
        .from(assignmentsTableName)
        .update(payload)
        .eq('ID', id)
        .is('Deleted_At', null)
        .select('ID,Duty_Date,Shift,Staff_ID,Status,Replacement_Staff_ID,Note,Created_At,Updated_At')
        .single();
      if (error) throw new Error(errorMessage('Update manpower assignment', error));
      return mapAssignmentRow(data);
    },

    async remove(id) {
      const { error } = await client
        .from(assignmentsTableName)
        .update({ Deleted_At: new Date().toISOString() })
        .eq('ID', id)
        .is('Deleted_At', null);
      if (error) throw new Error(errorMessage('Remove manpower assignment', error));
    },

    async importLocal(records = []) {
      const payload = records
        .filter(item => item?.date && item?.shift && item?.staffId)
        .map(item => {
          const row = assignmentPayload(item);
          delete row.ID;
          return row;
        });
      if (!payload.length) return 0;
      let imported = 0;
      // The active-assignment uniqueness rule is a partial index, which cannot
      // be targeted reliably by PostgREST upsert. Import one row at a time and
      // treat a database duplicate as an already-migrated record.
      for (const row of payload) {
        const { error } = await client.from(assignmentsTableName).insert(row);
        if (!error) {
          imported += 1;
          continue;
        }
        if (error.code === '23505') continue;
        throw new Error(errorMessage('Import local manpower assignments', error));
      }
      return imported;
    },

    subscribe(onChange) {
      if (channel) client.removeChannel(channel);
      channel = client
        .channel(`manpower-live-${crypto.randomUUID?.() || Date.now()}`)
        .on('postgres_changes', { event: '*', schema: 'public', table: assignmentsTableName }, payload => onChange?.('assignments', payload))
        .on('postgres_changes', { event: 'INSERT', schema: 'public', table: historyTableName }, payload => onChange?.('history', payload))
        .subscribe();
      return () => {
        if (channel) client.removeChannel(channel);
        channel = null;
      };
    }
  };
}

export { assignmentPayload, mapAssignmentRow, mapHistoryRow };
