-- Production-safety records for OPD encounter revisions and result acknowledgement.
-- Apply after 20260803090000_opd_test_visit_persistence.sql.

create table if not exists public."HIS_One_OPD_Encounter_Revisions" (
  "ID" bigint generated by default as identity primary key,
  "Visit_ID" text not null,
  "Patient_ID" text not null,
  "Revision" integer not null check ("Revision" > 0),
  "Status" text,
  "Discharge_Status" text,
  "Clinical_Note_JSON" jsonb not null,
  "Changed_By" text,
  "Changed_By_Name" text,
  "Changed_At" timestamptz not null default now(),
  constraint "uq_HIS_One_OPD_Encounter_Revisions_visit_revision"
    unique ("Visit_ID", "Revision")
);

create index if not exists "idx_HIS_One_OPD_Encounter_Revisions_patient_time"
  on public."HIS_One_OPD_Encounter_Revisions" ("Patient_ID", "Changed_At" desc);

comment on table public."HIS_One_OPD_Encounter_Revisions" is
  'Immutable snapshots written after each successful OPD Test EMR revision.';

create table if not exists public."HIS_One_Result_Acknowledgments" (
  "ID" bigint generated by default as identity primary key,
  "Result_File_ID" text not null,
  "Result_Type" text not null default 'lab'
    check ("Result_Type" in ('lab', 'ultrasound', 'xray', 'other')),
  "Order_ID" text,
  "Patient_ID" text,
  "Patient_Name" text,
  "Severity" text not null default 'normal'
    check ("Severity" in ('normal', 'abnormal', 'critical')),
  "Acknowledged_By" text not null,
  "Acknowledged_By_Name" text,
  "Acknowledged_At" timestamptz not null default now(),
  "Action_Note" text,
  constraint "uq_HIS_One_Result_Acknowledgments_file_user"
    unique ("Result_File_ID", "Acknowledged_By")
);

create index if not exists "idx_HIS_One_Result_Acknowledgments_user_time"
  on public."HIS_One_Result_Acknowledgments" ("Acknowledged_By", "Acknowledged_At" desc);

create index if not exists "idx_HIS_One_Result_Acknowledgments_critical"
  on public."HIS_One_Result_Acknowledgments" ("Severity", "Acknowledged_At" desc)
  where "Severity" = 'critical';

comment on table public."HIS_One_Result_Acknowledgments" is
  'Per-user clinical acknowledgement trail for laboratory and imaging results.';
